# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Make port 80 available to the world outside this container
EXPOSE 9092

# Run app.py when the container launches
CMD ["python", "consumerproducer.py"]
